Upload public file for config.json and add a *lot* of comments 😝
Signed-off-by: Chmouel Boudjnah <chmouel@redhat.com>

diff --git a/CI/tasks/openshift4-install.yaml b/CI/tasks/openshift4-install.yaml
--- a/CI/tasks/openshift4-install.yaml
+++ b/CI/tasks/openshift4-install.yaml
@@ -108,7 +108,19 @@ spec:
       #!/usr/bin/env bash
       set -eu
       [[ -n "$(inputs.params.UPLOADER_HOST)" ]] || exit 0
-      python $(inputs.resources.plumbing-git.path)/CI/misc/openshift-install-cleanup-route53.records.py -f $(inputs.params.CLUSTER_NAME)
+
+      # We are trying to delete the DNS record for the target install.
+      # Explaination:
+      # After the 'reaper' has reaped our openshift install in the aws account, it
+      # forget to delete some A records, so the reinstall fails :((
+      # let's be helpful and do it for the reaper ASAP....
+      python $(inputs.resources.plumbing-git.path)/CI/misc/openshift-install-cleanup-route53.records.py \
+             -f $(inputs.params.CLUSTER_NAME)
+
+      # We now try to get the metadata.json since that would give the
+      # information needed for the destroy clsuter command of the installer, if
+      # it's no there (we have been reaped already). Then let's just give up and
+      # hope for the best.
       curl -s -O $(inputs.params.UPLOADER_HOST)/$(inputs.params.CLUSTER_NAME)/metadata.json || exit
       echo "Trying to delete previous cluster (if it wasn't reaped already)"
       /usr/local/bin/openshift-install destroy cluster  --log-level=debug || true
@@ -130,8 +142,8 @@ spec:
     script: |
       #!/usr/bin/env bash
       set -e
+      # Launch install
       /usr/local/bin/openshift-install create cluster --log-level=debug
-      cat metadata.json
 
   - name: openshift-install-save-artifacts
     env:
@@ -156,12 +168,14 @@ spec:
       #!/usr/bin/env bash
       # We should probably set it in an external script but that's much easier
       # to iterate here atm.
-      set -ex
+      set -e
       gpg_args=
       key=
 
+      # Upload: by default it will upload the file as specified in "$1" to
+      # "$CLUSTER_NAME/basename of $1" if you specify a $2 it will upload the $1
+      # file to the destination specified in there.
       function upload() {
-        set -x
         dest="$2"
         [[ -z ${dest} ]] && dest="$(inputs.params.CLUSTER_NAME)/$(basename ${1})"
         curl -u ${UPLOADER_USERNAME}:${UPLOADER_PASSWORD} \
@@ -170,19 +184,36 @@ spec:
           $(inputs.params.UPLOADER_HOST)/upload/
       }
 
-      [[ -n "$(inputs.params.UPLOADER_HOST)" && -n ${UPLOADER_PUBRING} && -n ${UPLOADER_USERNAME} && -n ${UPLOADER_PASSWORD} ]] || exit 0
+      [[ -n $(inputs.params.UPLOADER_HOST) && \
+         -n ${UPLOADER_PUBRING} && \
+         -n ${UPLOADER_USERNAME} && \
+         -n ${UPLOADER_PASSWORD} ]] || exit 0
 
-      # Upload metadata.json asap
+      # We first upload the metadata.json generated by the openshfit
+      # install. This would help us delete it if needed.
       upload metadata.json
 
-      echo "${UPLOADER_PUBRING}" > /tmp/pubring.pgp
-      gpg --import /tmp/pubring.pgp
-      for key in $(gpg --list-public-keys --list-options no-show-photos --fingerprint --with-colons|awk -F: '$1 ~ /fpr/ {print $10}');do
-        gpg_args="$gpg_args -r$key"
-      done
-
+      # Zip the install.log for further inspection if needed.
+      # We save the last two lines of the installs log which contains easily
+      # readable information about how to to connect the cluster.
       bzip2 -9c .openshift_install.log > auth/install.log.bz2
       tail -2 .openshift_install.log > auth/webaccess
+
+      # Set the registry as public and export its config file.
+      export KUBECONFIG=auth/kubeconfig
+      oc login -u kubeadmin -p "$(cat auth/kubeadmin-password)" --insecure-skip-tls-verify
+      oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge
+      oc registry --insecure=true login --to=auth/registry.config.json
+
+      # We take all files and encrypt them to multiples gpg keys (openshift
+      # pipelines devs), we do as well for the logs to ensure no leakage can
+      # happen.
+      echo "${UPLOADER_PUBRING}" > /tmp/pubring.pgp
+      gpg --import /tmp/pubring.pgp
+      for key in $(gpg --list-public-keys --list-options no-show-photos \
+                   --fingerprint --with-colons|awk -F: '$1 ~ /fpr/ {print $10}');do
+        gpg_args="$gpg_args -r$key"
+      done
 
       for encryptfile in auth/*;do
         [[ -f ${encryptfile} ]] || continue
@@ -190,13 +221,12 @@ spec:
         upload ${encryptfile}.gpg
       done
 
+      # We are going to have two files than we are going to use for next tasks :
+      #
+      # $URL/private/${CLUSTER_NAME}/config.json -> config file to log to the
+      # target cluster's registry
+      #
+      # $URL/private/${CLUSTER_NAME}/kubeconfig -> the kubeconfig to access the
+      # say cluster registry
+      upload auth/registry.config.json private/$(inputs.params.CLUSTER_NAME)/config.json
       upload auth/kubeconfig private/$(inputs.params.CLUSTER_NAME)/kubeconfig
-
-      set -x
-      export KUBECONFIG=auth/kubeconfig
-      oc login -u kubeadmin -p "$(cat auth/kubeadmin-password)" --insecure-skip-tls-verify
-      oc patch configs.imageregistry.operator.openshift.io/cluster --patch '{"spec":{"defaultRoute":true}}' --type=merge
-      oc registry --insecure=true login --to=auth/registry.config.json
-
-      #TODO: encrypted to public too
-      upload auth/kubeconfig private/$(inputs.params.CLUSTER_NAME)/config.json
